### PR TITLE
Combine stylesheets/scripts to asset concatenation

### PR DESCRIPTION
**Pull request by akroii**

### CODE REVIEW

**Comment by klloe** [comment]
Looks fine, thanks for the PR. Didn't think someone is really using these extensions. :+1:

**Comment by akroii** [comment]
Emojis becoming more important in google's serps. Thats why your extension is useful.

**Comment by klloe** [comment]
Oh, didn't know they show up there, I've them never seen before. Did you solve the other issue?

**Comment by akroii** [comment]
I'am on it...

**Pull request merged**
